#
# Copyright 2020 Fraunhofer Institute for Software and Systems Engineering
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '3.5'

services:

  postgres-provider:
    image: postgres:13
    container_name: 'postgres-provider-container'
    ports:
      - "5433:5432"
    env_file:
      - ./postgres.env
    networks:
      - connector
    volumes:
      - provider-pg-data:/var/lib/postgresql/data

  provider:
    build:
      context: .
    container_name: 'provider-dataspace-connector'
    ports:
      - 8080:80
    env_file:
      - ./provider.env
    networks:
      - connector
    depends_on:
      - postgres-provider

  postgres-consumer:
    image: postgres:13
    container_name: 'postgres-consumer-container'
    ports:
      - "5434:5432"
    env_file:
      - ./postgres.env
    networks:
      - connector
    volumes:
      - consumer-pg-data:/var/lib/postgresql/data

  consumer:
    build:
      context: .
    container_name: 'consumer-dataspace-connector'
    ports:
      - 8081:80
    env_file:
      - ./consumer.env
    networks:
      - connector
    depends_on:
      - postgres-consumer


networks:
  connector:

volumes:
  provider-pg-data: {}
  consumer-pg-data: {}
